apiVersion: v1
kind: Template
metadata:
  name: cleanup-imagestream
  annotations:
    description: >
      This is Thoth CleanUp CronJob ImageStream, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: Thoth Cleanup CronJob ImageStream
    version: 0.8.0
    tags: thoth,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: >
      This is Thoth CleanUp CronJob ImageStream, this template is meant to be used by Bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: cleanup-imagestream
    app: thoth
    component: cleanup

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
        component: cleanup
      name: cleanup-job
    spec:
      name: latest
      lookupPolicy:
        local: true
